/**
 * Job Notification Tracker — 60 realistic Indian tech jobs
 */

window.JOB_TRACKER_JOBS = [
  {
    id: "1",
    title: "SDE Intern",
    company: "Amazon",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Data Structures", "Algorithms", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹50k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/1",
    description: "Work on large-scale distributed systems. You will design and implement features used by millions of customers. Mentorship from senior engineers and exposure to Amazon's leadership principles."
  },
  {
    id: "2",
    title: "Graduate Engineer Trainee",
    company: "TCS",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Spring Boot"],
    source: "Naukri",
    postedDaysAgo: 3,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/2",
    description: "Join our flagship graduate program. Rotate across projects in banking, retail, or healthcare. Comprehensive training in full-stack development and agile methodologies. Permanent role upon successful completion."
  },
  {
    id: "3",
    title: "Junior Backend Developer",
    company: "Razorpay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "Redis", "REST APIs"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/3",
    description: "Build and maintain APIs that power millions of transactions. You will work on payment processing, reconciliation, and developer tools. Strong code review culture and ownership from day one."
  },
  {
    id: "4",
    title: "Frontend Intern",
    company: "Freshworks",
    location: "Chennai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=4",
    description: "Contribute to our product UI used by 50,000+ businesses. Build reusable components, improve performance, and collaborate with design. Convert to full-time based on performance."
  },
  {
    id: "5",
    title: "QA Intern",
    company: "Wipro",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Manual Testing", "Selenium", "JIRA", "SQL"],
    source: "Naukri",
    postedDaysAgo: 5,
    salaryRange: "₹15k–₹25k/month Internship",
    applyUrl: "https://www.naukri.com/job/5",
    description: "Execute test cases for enterprise applications. Learn automation with Selenium and API testing. Work with global teams and gain exposure to DevOps and CI/CD pipelines."
  },
  {
    id: "6",
    title: "Data Analyst Intern",
    company: "Flipkart",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Excel", "Tableau"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹20k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/6",
    description: "Analyze customer and supply chain data to drive decisions. Build dashboards and reports for category and operations teams. Exposure to big data tools and e-commerce metrics."
  },
  {
    id: "7",
    title: "Java Developer (0-1)",
    company: "Infosys",
    location: "Pune",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring", "Hibernate", "MySQL"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/7",
    description: "Develop and maintain Java applications for our clients in banking and insurance. Work in agile squads with code reviews and unit testing. Training on cloud and microservices provided."
  },
  {
    id: "8",
    title: "Python Developer (Fresher)",
    company: "Zoho",
    location: "Chennai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Linux"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/8",
    description: "Build features for Zoho's product suite. We hire for potential and train in-house. Flat structure, no managers—teams self-organize. Long-term career with stock options."
  },
  {
    id: "9",
    title: "React Developer (1-3)",
    company: "Swiggy",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "Jest"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/9",
    description: "Own the consumer app experience for millions of orders. Work on performance, accessibility, and new features. Strong design partnership and A/B testing culture."
  },
  {
    id: "10",
    title: "SDE Intern",
    company: "Microsoft",
    location: "Hyderabad",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C#", "Azure", "Algorithms", "SQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹40k–₹60k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/10",
    description: "Intern on Azure, Office, or Windows teams. Ship code to production with mentorship. Many interns receive pre-placement offers. Relocation and housing support provided."
  },
  {
    id: "11",
    title: "Graduate Engineer Trainee",
    company: "Accenture",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Cloud", "Agile", "SQL"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/11",
    description: "Join our technology development program. Work on digital transformation projects for Fortune 500 clients. Training in cloud, security, and full-stack development."
  },
  {
    id: "12",
    title: "Junior Backend Developer",
    company: "PhonePe",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Kafka", "Cassandra", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/12",
    description: "Build scalable backend services for payments and lending. High scale, low latency systems. Work with product and data teams in a fast-paced environment."
  },
  {
    id: "13",
    title: "Frontend Intern",
    company: "CRED",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "Next.js", "TypeScript", "Tailwind"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/13",
    description: "Work on the member app and internal tools. Modern stack, design system, and high bar for UX. Small team, high impact. Potential to convert to full-time."
  },
  {
    id: "14",
    title: "Data Analyst Intern",
    company: "Juspay",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Spark", "Data pipelines"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=14",
    description: "Analyze payment success rates and fraud patterns. Build dashboards for product and risk teams. Work with large-scale transaction data and ML models."
  },
  {
    id: "15",
    title: "Java Developer (0-1)",
    company: "Cognizant",
    location: "Coimbatore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "REST", "Oracle"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/15",
    description: "Develop enterprise applications for healthcare and financial services clients. Follow agile and DevOps practices. Opportunity to work with global delivery teams."
  },
  {
    id: "16",
    title: "React Developer (1-3)",
    company: "Paytm",
    location: "Noida",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "JavaScript", "Redux", "Webpack"],
    source: "Naukri",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/job/16",
    description: "Build and maintain Paytm's consumer and merchant web apps. Focus on performance and reliability at scale. Work with design and backend in cross-functional squads."
  },
  {
    id: "17",
    title: "SDE Intern",
    company: "Google",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "Python", "Algorithms", "System Design"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹50k–₹70k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/17",
    description: "Twelve-week internship on Search, Ads, Cloud, or Android. Work on real problems with a host and mentor. Strong conversion rate to full-time offers."
  },
  {
    id: "18",
    title: "Graduate Engineer Trainee",
    company: "Capgemini",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: [".NET", "C#", "SQL Server", "Azure"],
    source: "Indeed",
    postedDaysAgo: 8,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=18",
    description: "Join our engineering graduate program. Work on cloud migration and application development for European clients. Training and certifications sponsored."
  },
  {
    id: "19",
    title: "Junior Backend Developer",
    company: "Dunzo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Python", "Django", "PostgreSQL", "Celery"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/19",
    description: "Build APIs for delivery and merchant operations. Work on order routing, tracking, and partner apps. Fast-paced startup with strong engineering culture."
  },
  {
    id: "20",
    title: "Frontend Intern",
    company: "Postman",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "APIs", "GraphQL"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/20",
    description: "Contribute to Postman's web and desktop app. Build features used by 25M+ developers. Collaborative team, async-friendly, and global remote culture."
  },
  {
    id: "21",
    title: "QA Intern",
    company: "IBM",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Test Automation", "Java", "Selenium", "Jenkins"],
    source: "Naukri",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://www.naukri.com/job/21",
    description: "Support quality assurance for IBM software products. Develop automated tests and integrate with CI/CD. Exposure to enterprise software development lifecycle."
  },
  {
    id: "22",
    title: "Python Developer (Fresher)",
    company: "Oracle",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Python", "SQL", "Linux", "Scripting"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=22",
    description: "Work on Oracle Cloud infrastructure or database tooling. Scripting, automation, and integration tasks. Clear path to full-time conversion after internship."
  },
  {
    id: "23",
    title: "React Developer (1-3)",
    company: "ShareChat",
    location: "Bangalore",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "React Native", "TypeScript", "State management"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/23",
    description: "Build the creator and consumer experience for our short-video and social apps. Work on feed, upload, and engagement features. High traffic and real-time systems."
  },
  {
    id: "24",
    title: "SDE Intern",
    company: "Intuit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "React", "AWS", "Databases"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹40k–₹55k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/24",
    description: "Intern on TurboTax, QuickBooks, or Mailchimp. Ship customer-facing features with mentorship. Inclusive culture and focus on work-life balance."
  },
  {
    id: "25",
    title: "Graduate Engineer Trainee",
    company: "L&T Infotech",
    location: "Mumbai",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Angular", "SQL", "Cloud basics"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/25",
    description: "Join our digital engineering unit. Work on web and mobile projects for manufacturing and energy clients. Structured training and certification support."
  },
  {
    id: "26",
    title: "Junior Backend Developer",
    company: "Unacademy",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "MongoDB", "Redis", "GraphQL"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=26",
    description: "Build APIs for live classes, content, and payments. Work on scalability and real-time features. EdTech scale-up with strong engineering team."
  },
  {
    id: "27",
    title: "Data Analyst Intern",
    company: "Ola",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Visualization"],
    source: "LinkedIn",
    postedDaysAgo: 5,
    salaryRange: "₹22k–₹38k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/27",
    description: "Analyze ride and driver data to improve supply and demand. Build reports for city and central teams. Exposure to mobility and logistics metrics."
  },
  {
    id: "28",
    title: "Java Developer (0-1)",
    company: "SAP",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "SAP Cloud", "REST", "OData"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/28",
    description: "Develop extensions and integrations for SAP cloud products. Work with enterprise customers and internal product teams. Training on SAP technologies provided."
  },
  {
    id: "29",
    title: "Frontend Intern",
    company: "BrowserStack",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "Testing", "Web APIs"],
    source: "Indeed",
    postedDaysAgo: 1,
    salaryRange: "₹28k–₹42k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=29",
    description: "Help build the BrowserStack dashboard and developer tools. Work on front-end for a product used by millions of developers. Remote-first, async culture."
  },
  {
    id: "30",
    title: "React Developer (1-3)",
    company: "Dell",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "TypeScript", "Redux", "REST"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.naukri.com/job/30",
    description: "Build internal and customer-facing web applications for Dell's infrastructure and client solutions. Work with global teams and modern front-end practices."
  },
  {
    id: "31",
    title: "SDE Intern",
    company: "Thoughtworks",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "TDD", "Pair Programming", "Agile"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "₹35k–₹50k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/31",
    description: "Intern with our consulting teams on client projects. Emphasis on clean code, testing, and delivery. Diverse projects across domains and technologies."
  },
  {
    id: "32",
    title: "Graduate Engineer Trainee",
    company: "HCL Technologies",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Python", "SQL", "Cloud"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/32",
    description: "Join our engineering graduate program. Work on application development and maintenance for global clients. Training in emerging technologies and soft skills."
  },
  {
    id: "33",
    title: "Junior Backend Developer",
    company: "Dealshare",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Python", "Django", "MySQL", "Redis"],
    source: "Indeed",
    postedDaysAgo: 2,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=33",
    description: "Build backend services for e-commerce and supply chain. Work on catalog, search, and order flows. Fast-growing startup in the social commerce space."
  },
  {
    id: "34",
    title: "Python Developer (Fresher)",
    company: "HackerRank",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "REST"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/34",
    description: "Work on our assessment and interview platform. Build features for candidates and hiring teams. Remote-first, small team, high ownership."
  },
  {
    id: "35",
    title: "QA Intern",
    company: "Mindtree",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Postman", "JIRA"],
    source: "Naukri",
    postedDaysAgo: 6,
    salaryRange: "₹18k–₹28k/month Internship",
    applyUrl: "https://www.naukri.com/job/35",
    description: "Execute functional and regression tests for enterprise applications. Learn API and performance testing. Work in agile teams with BAs and developers."
  },
  {
    id: "36",
    title: "React Developer (1-3)",
    company: "CleverTap",
    location: "Mumbai",
    mode: "Remote",
    experience: "1-3",
    skills: ["React", "JavaScript", "D3.js", "Product analytics"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/36",
    description: "Build dashboards and visualizations for our analytics platform. Work on real-time data and complex UI. B2B SaaS product used by top brands globally."
  },
  {
    id: "37",
    title: "SDE Intern",
    company: "Adobe",
    location: "Noida",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["C++", "JavaScript", "Algorithms", "Data structures"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹45k–₹60k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/37",
    description: "Intern on Creative Cloud, Document Cloud, or Experience Cloud. Work on features used by creatives and enterprises. Strong mentorship and conversion opportunities."
  },
  {
    id: "38",
    title: "Data Analyst Intern",
    company: "Myntra",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Python", "Excel", "Looker"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹20k–₹35k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=38",
    description: "Analyze fashion and customer data for category and marketing teams. Build reports and dashboards. Exposure to e-commerce analytics and experimentation."
  },
  {
    id: "39",
    title: "Java Developer (0-1)",
    company: "Publicis Sapient",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "0-1",
    skills: ["Java", "Spring", "Kafka", "Microservices"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.naukri.com/job/39",
    description: "Build digital solutions for retail and travel clients. Work in agile pods with designers and architects. Training on cloud and modern Java ecosystem."
  },
  {
    id: "40",
    title: "Frontend Intern",
    company: "Reverie Language Technologies",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "Localization", "i18n"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹22k–₹32k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/40",
    description: "Work on language and localization products. Build UI for translation and voice tools. Impact on Indian language technology and accessibility."
  },
  {
    id: "41",
    title: "Junior Backend Developer",
    company: "Slice",
    location: "Bangalore",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Go", "PostgreSQL", "Redis", "gRPC"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/41",
    description: "Build backend for card and rewards products. High-throughput, low-latency systems. Fintech startup with strong engineering and design culture."
  },
  {
    id: "42",
    title: "Graduate Engineer Trainee",
    company: "Tech Mahindra",
    location: "Pune",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Selenium", "DevOps basics", "SQL"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/42",
    description: "Join our digital services unit. Work on testing, development, or support for telecom and manufacturing clients. Comprehensive induction and role-based training."
  },
  {
    id: "43",
    title: "React Developer (1-3)",
    company: "Livspace",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "1-3",
    skills: ["React", "Redux", "Responsive design", "REST"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=43",
    description: "Build the customer and designer experience for home interior platform. Work on configurators, catalog, and booking flows. Design-led product team."
  },
  {
    id: "44",
    title: "SDE Intern",
    company: "Groww",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["Java", "React", "SQL", "System design basics"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹30k–₹45k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/44",
    description: "Work on our investing or mutual funds platform. Ship features for millions of users. Fintech scale-up with focus on simplicity and reliability."
  },
  {
    id: "45",
    title: "Python Developer (Fresher)",
    company: "Rebel Foods",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "PostgreSQL", "Celery"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=45",
    description: "Build internal tools and APIs for cloud kitchen operations. Work on menu, orders, and logistics. Fast-paced food tech with strong engineering team."
  },
  {
    id: "46",
    title: "QA Intern",
    company: "Meesho",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "API Testing", "Mobile Testing", "JIRA"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹20k–₹30k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/46",
    description: "Test the Meesho seller and reseller app. Create test cases and report bugs. Exposure to e-commerce and social commerce flows at scale."
  },
  {
    id: "47",
    title: "Java Developer (0-1)",
    company: "Altimetrik",
    location: "Chennai",
    mode: "Onsite",
    experience: "0-1",
    skills: ["Java", "Spring Boot", "MongoDB", "REST"],
    source: "Naukri",
    postedDaysAgo: 7,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/47",
    description: "Develop microservices for digital banking and insurance clients. Work in agile teams with CI/CD. Training on cloud and container technologies."
  },
  {
    id: "48",
    title: "Data Analyst Intern",
    company: "Policybazaar",
    location: "Gurgaon",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "Reporting"],
    source: "Indeed",
    postedDaysAgo: 3,
    salaryRange: "₹18k–₹28k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=48",
    description: "Analyze insurance and customer data. Support product and growth teams with reports. Exposure to fintech and conversion analytics."
  },
  {
    id: "49",
    title: "Frontend Intern",
    company: "Vedantu",
    location: "Bangalore",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "HTML", "CSS"],
    source: "LinkedIn",
    postedDaysAgo: 4,
    salaryRange: "₹25k–₹35k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/49",
    description: "Build UI for live classes and learning content. Work with design and product on student and teacher experience. EdTech with focus on quality and scale."
  },
  {
    id: "50",
    title: "React Developer (1-3)",
    company: "Licious",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "TypeScript", "PWA", "State management"],
    source: "LinkedIn",
    postedDaysAgo: 0,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/50",
    description: "Own the consumer app for meat and seafood delivery. Work on cart, checkout, and personalization. D2C brand with strong supply chain and tech."
  },
  {
    id: "51",
    title: "SDE Intern",
    company: "Innovaccer",
    location: "Noida",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "SQL", "Healthcare data", "APIs"],
    source: "Indeed",
    postedDaysAgo: 5,
    salaryRange: "₹28k–₹40k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=51",
    description: "Work on healthcare analytics and care coordination platform. Build features for providers and payers. Mission-driven health tech with global customers."
  },
  {
    id: "52",
    title: "Graduate Engineer Trainee",
    company: "Mphasis",
    location: "Bangalore",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["Java", "Mainframe", "SQL", "COBOL basics"],
    source: "Naukri",
    postedDaysAgo: 10,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/52",
    description: "Join our application development stream. Work on legacy modernization or new development for BFSI clients. Training and certification support."
  },
  {
    id: "53",
    title: "Junior Backend Developer",
    company: "Acko",
    location: "Bangalore",
    mode: "Remote",
    experience: "0-1",
    skills: ["Node.js", "PostgreSQL", "AWS", "Microservices"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "6–10 LPA",
    applyUrl: "https://www.linkedin.com/jobs/view/53",
    description: "Build APIs for insurance products and claims. Work on pricing, policies, and integrations. InsurTech with product-first engineering culture."
  },
  {
    id: "54",
    title: "Python Developer (Fresher)",
    company: "GrayQuest",
    location: "Mumbai",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Python", "Django", "REST", "PostgreSQL"],
    source: "Indeed",
    postedDaysAgo: 6,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.indeed.com/viewjob?jk=54",
    description: "Build backend for education fee financing platform. Work on lender and school integrations. Fintech startup with focus on education segment."
  },
  {
    id: "55",
    title: "QA Intern",
    company: "Practo",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Manual Testing", "Mobile", "API", "JIRA"],
    source: "LinkedIn",
    postedDaysAgo: 3,
    salaryRange: "₹18k–₹26k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/55",
    description: "Test the Practo app for patients and doctors. Functional and regression testing. Exposure to health tech and appointment booking flows."
  },
  {
    id: "56",
    title: "React Developer (1-3)",
    company: "NoBroker",
    location: "Bangalore",
    mode: "Onsite",
    experience: "1-3",
    skills: ["React", "React Native", "JavaScript", "REST"],
    source: "Naukri",
    postedDaysAgo: 8,
    salaryRange: "10–18 LPA",
    applyUrl: "https://www.naukri.com/job/56",
    description: "Build the tenant and owner experience for property search and transactions. Work on listing, search, and payments. Proptech with pan-India presence."
  },
  {
    id: "57",
    title: "SDE Intern",
    company: "Cure.fit",
    location: "Bangalore",
    mode: "Hybrid",
    experience: "Fresher",
    skills: ["Java", "Python", "Mobile basics", "APIs"],
    source: "LinkedIn",
    postedDaysAgo: 2,
    salaryRange: "₹25k–₹40k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/57",
    description: "Work on fitness or mental health products. Build features for classes, subscriptions, and content. Health and wellness tech with multiple apps."
  },
  {
    id: "58",
    title: "Data Analyst Intern",
    company: "Delhivery",
    location: "Gurgaon",
    mode: "Onsite",
    experience: "Fresher",
    skills: ["SQL", "Excel", "Python", "Logistics metrics"],
    source: "Indeed",
    postedDaysAgo: 4,
    salaryRange: "₹20k–₹32k/month Internship",
    applyUrl: "https://www.indeed.com/viewjob?jk=58",
    description: "Analyze delivery and network data. Build reports for operations and city teams. Exposure to logistics and last-mile delivery analytics."
  },
  {
    id: "59",
    title: "Java Developer (0-1)",
    company: "Navant",
    location: "Chennai",
    mode: "Remote",
    experience: "0-1",
    skills: ["Java", "Spring", "AWS", "REST"],
    source: "Naukri",
    postedDaysAgo: 9,
    salaryRange: "3–5 LPA",
    applyUrl: "https://www.naukri.com/job/59",
    description: "Develop enterprise applications for global clients. Work on cloud migration and microservices. Mid-size product and services company."
  },
  {
    id: "60",
    title: "Frontend Intern",
    company: "Fynd",
    location: "Mumbai",
    mode: "Remote",
    experience: "Fresher",
    skills: ["React", "JavaScript", "E-commerce", "Responsive"],
    source: "LinkedIn",
    postedDaysAgo: 1,
    salaryRange: "₹22k–₹35k/month Internship",
    applyUrl: "https://www.linkedin.com/jobs/view/60",
    description: "Build storefront and merchant tools for fashion e-commerce. Work on product pages, cart, and checkout. Omnichannel retail tech with strong design."
  }
];
